trigger:

- main
 
pool:

  Superman
 
jobs:

- job: RunPythonScriptJob

  displayName: 'Run Python Script'

  steps:

  - checkout: self
 
  - script: |

      sudo yum install python3 -y
      sudo yum install django -y

    displayName: 'Install Python 3'
 
  - script: |

      echo "export GITHUB_TOKEN=$GITHUB_TOKEN" >> ~/.bashrc

      source ~/.bashrc

      python3 index.py

    displayName: 'Run Your Python Script'

    env:

      GITHUB_TOKEN: $(GITHUB_TOKEN)
