kind: Deployment
apiVersion: apps/v1
metadata:
  name: weatherdeployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      name: weatherpod
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherautomationcontainer1
        image: saitheja12/weather-automation1
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        ports:
        - containerPort: 8000
