apiVersion: v1

kind: Service

metadata:

  name: weatherservice2

spec:

  type: NodePort

  selector:

    app: weatherapp

  ports:

    - port: 8000

      targetPort: 8000

      nodePort: 31567 # You can change this to any available port number above 30000
