apiVersion: v1

kind: Service

metadata:

  name: weather-automation-service

spec:

  type: NodePort

  selector:

    app: weatherapp

  ports:

    - port: 8000

      targetPort: 8000

      nodePort: 31467 # You can change this to any available port number above 30000
